name: "Install Releaser"
description: "Ensure Releaser is Installed"
runs:
  using: "composite"
  steps:
    - shell: bash
      id: install-releaser
      run: |
        set -eux
        # Install Jupyter Releaser if it is not already installed
        if ! command -v jupyter-releaser &> /dev/null
        then
            cd "${{ github.action_path }}"
            cd ../../..
            pip install -e .
        fi
