name: "Install Releaser"
description: "Ensure Releaser is Installed"
runs:
  using: "composite"
  steps:
    - shell: bash
      id: install-releaser
      run: |
        bash "${{ github.action_path }}"/../scripts/install-releaser.sh
